name: "GitHub Actions Application Deployment"

on:
  push:
    branches:
      - main

jobs:
  Deploy-flow:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: npm install dependencies
        run: npm ci

      - name: check versions
        run: |
          node --version
          npm --version

      - name: Deplying application
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          script: |
            cd /home/ubuntu/github-actions-cicd2

            git pull origin main

            echo "PORT= ${{ vars.PORT }}" > .env

            docker compose down 
            docker compose up -d --build

            docker ps

      - name: print welcome message
        run: echo "Github actions workflow started succesfully"

      - name: Checkout operating system
        run: uname -a

      - name: Checkout Current Directory
        run: pwd

      - name: list Directories
        run: ls -la
